services:
  php:
    build: .
    container_name: nomdusite_php
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: Melody
      MYSQL_PASSWORD: Melody!Root2025
      MYSQL_DATABASE: blog_jdr

  mailer:
    image: axllent/mailpit
    ports:
      - '1025'
      - '8025'
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  mariadb:
    image: mariadb:11.2
    container_name: nomdusite_mariadb
    environment:
      MYSQL_USER: Melody
      MYSQL_PASSWORD: Melody!Root2025
      MYSQL_DATABASE: blog_jdr
      MYSQL_ROOT_PASSWORD: Melody!Root2025
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./database/blog_jdr.sql:/docker-entrypoint-initdb.d/init.sql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nomdusite_phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - '8080:80'
    depends_on:
      - mariadb

volumes:
  db_data:
